//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoClinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int idCita { get; set; }
        public int idMedico { get; set; }
        public int idPaciente { get; set; }
        public int idEnfermedad { get; set; }
    
        public virtual Ordenes Ordenes { get; set; }
        public virtual Enfermedades Enfermedades { get; set; }
        public virtual Medicos Medicos { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
