//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoClinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicamentosConsultas
    {
        public int idMConsulta { get; set; }
        public int idMedicamento { get; set; }
        public int idConsulta { get; set; }
    
        public virtual Medicamentos Medicamentos { get; set; }
        public virtual Ordenes Ordenes { get; set; }
    }
}
